metadata:
  name: ${project.artifactId}-d
  labels:
    app.openshift.io/runtime: spring-boot  
spec:
  replicas: 3
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
        - resources: 
            requests:
              memory: "1Gi"
              cpu: "1000m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
          readinessProbe:
            httpGet:
              path: /rest/server
              port: 8090
              scheme: HTTP
              httpHeaders:
                - name: Authorization
                  value: Basic a2llc2VydmVyOmtpZXNlcnZlcjEh
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8090
              scheme: HTTP
            initialDelaySeconds: 30
            failureThreshold: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%